### ISSUE TITLE
Getting all currently registered stub mappings

### ISSUE THREAD

**Issue by StefH** [StefH/WireMock.Net#12]

**Comment by gregoks** [comment]
Hi,

I was wondering if this is implemented? Because I see now that RequestMatchers in RequestMessageCompositeMatcher class is private. So is there a way we can get the instance of all registered mappings like we see them in the admin API?

Thx,

Greg

**Comment by StefH** [comment]
Hello Greg; you can just access `Mappings` ?

Like
https://github.com/WireMock-Net/WireMock.Net/blob/12444cc11e0c806a2436e2a823227dc757781b29/test/WireMock.Net.Tests/FluentMockServerTests.Settings.cs#L102

**Comment by gregoks** [comment]
Yeah but its an interface of IMapping, I want to be able to serialize it and send it as an object over http. Thats why I need the mapping info like path, request matchers, response etc as properties.

**Comment by StefH** [comment]
You know you can just do a GET request to the `/__admin/mappings` to get all mappings?

**Comment by gregoks** [comment]
Yeah I know but since I have the server object in memory, I was wondering if I could get the mappings the same way as I can get LogEntries without the need of extra http call

**Comment by StefH** [comment]
I see, can you create a new issue?

**Comment by StefH** [comment]
https://github.com/WireMock-Net/WireMock.Net/pull/298

**Comment by gregoks** [comment]
Thanks @StefH for the quick response! I'll create an issue now.
