### ISSUE TITLE
Consider port to .Net Core

### ISSUE THREAD

**Issue by sbebrys** [StefH/WireMock.Net#23]
Hi, are You consider to port and support only .Net Standard version of this project?
I port it now to .net standard 1.3  [sbebrys/WireMock.Net](https://github.com/sbebrys/WireMock.Net) but You need port XPath2 too.

**Comment by StefH** [comment]
I did consider this already : https://github.com/StefH/WireMock.Net/blob/master/src/WireMock.Net/netstandard1.3.txt

However XPath / XPath2 are both not supported on netstandard 1.3 or even not on netstandard 1.6 if I remember correctly.

Maybe the new structures in vs2017 can help/support this, but I dont think it will work.

If XPath is the only one which gives troubles, I can remove it and create a new NuGet package which is an extension on this one.

**Comment by StefH** [comment]
Also Handlebars.Net is still old version on NuGet.

I created a PR which was merged to main, however no new NuGet yet. Maybe you can alsonssk for a new version?

**Comment by sbebrys** [comment]
Ok, so I asked Handlebars about new release and we could wait for it.

**Comment by StefH** [comment]
Btw : The http listener is also not present in netstandard 1.3

But we can try to use this one : https://github.com/StefH/NETStandard.HttpListener

**Comment by sbebrys** [comment]
I saw that, but this version doesn't support yet ContentLength and ContentEncoding, I did workaround this by using [custom headers](https://github.com/sbebrys/WireMock.Net/blob/master/src/WireMock.Net/HttpListenerResponseMapper.cs#L35) but it isn't the best solution. In my project it satisfy me, but I don't think it is ok for everyone.

**Comment by StefH** [comment]
Can you maybe make a PR on NETStandard.HttpListener and then move this PR into my `https://github.com/StefH/WireMock.Net/tree/_stef_netstandard` branch?

**Comment by StefH** [comment]
I removed the `HttpListener` and used `Microsoft.AspNetCore`
