### ISSUE TITLE
Facing issue with WildcardMatcher and '?'

### ISSUE THREAD

**Issue by pradkhanna** [StefH/WireMock.Net#28]
Hi 
I'm building a mock response for the uri...
 /config/api/foundation/economic-regions/search?channel=1&brand=2

though the mock is setup...  I'm getting response for all characters except ? in the uri.
like, 
/config/api/foundation/economic-regions/searchachannel=1&brand=2
/config/api/foundation/economic-regions/search.channel=1&brand=2

From the code here, I see the Regex Replace(@"\?", ".") 

How do I build the mock for my uri? Please Help.

**Comment by StefH** [comment]
I guess you want to match parameters?
Then you can use something like:
```c#
... Create().WithParam("bar", "1", "2");
```

which will match an url like : `http://localhost/foo?bar=1&bar=2`

**Comment by pradkhanna** [comment]
Thanks StefH.
But, I'm using a .json configured mapping something like this....
{
  "Request": {
    "Path": {
      "Matchers": [
        {
          "Name": "WildcardMatcher",
          "Pattern": "/config/api/foundation/economic-regions/search"
        }
      ]
    },
    "Methods": [
      "get"
    ]
  },
  "Response": {
    "BodyAsJson": _{"Response_Json": "Goes here"}_,
    "Headers": {
      "Content-Type": "application/json"
    }
  }
}

so your **Create().WithParam("bar", "1", "2");** would be a ## RequestMessageParamMatcher?  and at what level in the above config .json's "Request" would it go?

**Comment by StefH** [comment]
Maybe a better option would be to use the RegexMatcher to create a regular expression which matches your url

**Comment by pradkhanna** [comment]
Sorry for the late response.  I've got the response mapped using .withParam();   and got my mapping.json file configured using it.   Thanks again.

**Comment by StefH** [comment]
Cool !
