### ISSUE TITLE
[Feature] Disable partial mappings by default in standalone version

### ISSUE THREAD

**Issue by phillee007** [StefH/WireMock.Net#30]
In the standalone code, it has AllowPartialMapping set to true by default. Perhaps this should be set to false by default as it can be very confusing when debugging and seeing results being returned for things that you don't expect?

```
[SwitchArgument("AllowPartialMapping", true, Description = "Allow Partial Mapping (default set to true).", Optional = true)]
public bool AllowPartialMapping { get; set; }
```

**Comment by StefH** [comment]
done

https://github.com/StefH/WireMock.Net/commit/97c7a153020b3fa468d5b563e5cd5cc411887d32
