### ISSUE TITLE
Feature request: Nuget package for standalone version

### ISSUE THREAD

**Issue by phillee007** [StefH/WireMock.Net#31]
Was there an earlier version where the standalone console app was also available via a Nuget package? 

I can't see one now, and it would be useful to have one. Yes it's easy to create my own console app and copy/paste the Wiremock.Standalone code into it, but would be even easier to have a nuget package for it :-)

Thanks,
Phil

**Comment by StefH** [comment]
Try https://www.nuget.org/packages/WireMock.Net.StandAlone/1.0.0
