### ISSUE TITLE
Issue with launching sample code (StandAlone server)

### ISSUE THREAD

**Issue by Yopt** [StefH/WireMock.Net#33]
Dear WireMock team,

there is an issue with launching sample code:
Unhandled Exception: System.TypeLoadException: Could not load type 'WireMock.Settings.FluentMockServerSettings' from assembly 'WireMock.Net, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null'.
   at WireMock.Net.StandAlone.StandAloneApp.Start(String[] args)
   at WireMock.Net.StandAlone.Program.Main(String[] args) 

```
using System;
namespace WireMock.Net.StandAlone
{
    public class Program
    {
        static void Main(params string[] args)
        {
            StandAloneApp.Start(args);

            Console.WriteLine("Press any key to stop the server");
            Console.ReadKey();
        }
    }
}
```

**Comment by Yopt** [comment]
@StefH

**Comment by StefH** [comment]
Thanks for reporting. I'll take a look.

**Comment by StefH** [comment]
Upgrade WireMock.Net to:
https://www.nuget.org/packages/WireMock.Net/1.0.2.1

**Comment by Yopt** [comment]
@StefH now it`s ok, thank you

**Comment by StefH** [comment]
I've also uploaded a new StandAlone NuGet which does reference this fixed WireMock.Net dependency.
